### ISSUE TITLE
Support multiple titles for multiple selectors

### ISSUE THREAD

**Issue by mayday6971** [vanderlee/limitslider#11]
Hello,

I am working on a project where the customer has a requirement that the mouseovers are different between the two range sliders that are added to the limitslider. As it stands, the code only allows for one mouseover title. I tried making a function to figure out the value (values[0] or values[1]) however this isn't easily accessible from the title callback function. I'll be glad to provide more information if you would like.

Thanks,
Tim

**Comment by mayday6971** [comment]
Here is my declaration call. You pass in the sliderDiv, and there are a minimum and maximum I store in hidden form fields.  The title callback has value and I can log out the entire object, but there isn't a lot I can use to figure out if this is the minimum or maximum slider.

```javascript
function setupSliderBar(sliderDiv, minimumInput, maximumInput) {
  sliderDiv.limitslider({
    range: true,
    animate: "slow",
    gap: 20,
    min: 0,
    max: 100,
    values: [ 0, 100 ],
    slide: function( event, ui ) {
      minimumInput.val( ui.values[0] );
      maximumInput.val( ui.values[1] );
    },
    title: function (value) {
      //console.log(this);
      //console.log(value);
      return 'Currently set to '+value+'%';
    },
    showRanges: true,
    label: true,
    ranges: [false, { styleClass: 'range-glow' }, false, true]
  });
}
```

**Comment by vanderlee** [comment]
The easiest fix would probably be to include the index of the slider as second argument to the `title` callback. Would that suffice in your case?

**Comment by mayday6971** [comment]
Thanks, this fixes my issue perfectly. 

Tim
