### ISSUE TITLE
Can't get slider to work

### ISSUE THREAD

**Issue by ascourtas** [vanderlee/limitslider#13]
Hello, I have the JQuery UI Slider Widget, and I had another slider library that was also based on the JQuery Slider work, but I cannot get your slider to work. Any suggestions? I have styled the slider divs appropriately.

The slider shows up in my browser, but does not slide.

**Comment by vanderlee** [comment]
Do you have an example online (i.e. on jsfiddle) that demonstrates the problem?
As is, this is far too little information. Best I can suggest at this moment is to check jQueryUI version.

**Comment by ascourtas** [comment]
Actually I figured out the problem, my mistake -- there was a typo when I included the link to the JQuery CSS.
