### ISSUE TITLE
Slider doesn't slide on click of the button

### ISSUE THREAD

**Issue by TameshwarNirmalkar** [vanderlee/limitslider#5]
var myslider = $('#basic').limitslider({
		    values: [140, 160, 180, 200],
		    value:''
});
$('btn1').on('click', function(){
  myslider.limitslider('values', 1, 10);
});

it only moves the handler the not the bar.

Example link for test.
http://jsfiddle.net/qkwjoLcz/14/

**Comment by vanderlee** [comment]
I've added a fix for this issue.
Could you please test the current version and close this issue if correct?

**Comment by TameshwarNirmalkar** [comment]
yes it is working..
